import express from 'express';
const router = express.Router();
import axios from 'axios';
import crypto from 'crypto';
import prisma from '../db/prisma.js';

// PayU v2 configuration
const PAYU_BASE_URL = process.env.PAYU_ENV === 'production' 
  ? 'https://api.payu.in' 
  : 'https://apitest.payu.in';

const PAYU_MERCHANT_KEY = process.env.PAYU_MERCHANT_KEY || 'your-merchant-key';
const PAYU_MERCHANT_SALT = process.env.PAYU_MERCHANT_SALT || 'your-merchant-salt';
const PAYU_AUTH_HEADER = process.env.PAYU_AUTH_HEADER || 'your-auth-header';

// Helper function to generate PayU v2 signature
const generateSignature = (data, salt) => {
  const hashString = `${data}|${salt}`;
  return crypto.createHash('sha512').update(hashString).digest('hex');
};

// Helper function to verify PayU webhook signature
const verifyWebhookSignature = (body, signature) => {
  const expectedSignature = generateSignature(JSON.stringify(body), PAYU_MERCHANT_SALT);
  return expectedSignature === signature;
};

// Create PayU v2 order
router.post('/create-order', async (req, res) => {
  try {
    const { amount, productinfo, firstname, email, phone, udf1, udf2, udf3, udf4, udf5 } = req.body;
    
    // Generate unique transaction ID
    const txnid = 'TXN' + Date.now() + Math.floor(Math.random() * 1000);
    
    // Prepare order data for PayU v2
    const orderData = {
      txnid: txnid,
      amount: amount,
      productinfo: productinfo,
      firstname: firstname,
      email: email,
      phone: phone,
      udf1: udf1 || '',
      udf2: udf2 || '',
      udf3: udf3 || '',
      udf4: udf4 || '',
      udf5: udf5 || '',
      surl: `${req.headers.origin || 'http://localhost:3000'}/api/payu-v2/success`,
      furl: `${req.headers.origin || 'http://localhost:3000'}/api/payu-v2/failure`,
      key: PAYU_MERCHANT_KEY
    };
    
    // Create order in our database first
    const order = await prisma.payments.create({
      data: {
        orderId: txnid,
        userId: udf1 || null, // Assuming udf1 contains user ID
        amount: parseFloat(amount),
        currency: 'INR',
        status: 'pending',
        gatewayResponse: JSON.stringify(orderData)
      }
    });
    
    res.json({
      success: true,
      orderId: txnid,
      order
    });
  } catch (error) {
    console.error('Error creating PayU order:', error);
    res.status(500).json({ 
      success: false, 
      error: 'Failed to create PayU order',
      message: error.message 
    });
  }
});

// PayU v2 payment initiation
router.post('/initiate-payment', async (req, res) => {
  try {
    const { orderId, amount, productinfo, firstname, email, phone } = req.body;
    
    // Get order from database
    const order = await prisma.payments.findUnique({
      where: { orderId: orderId }
    });
    
    if (!order) {
      return res.status(404).json({ 
        success: false, 
        error: 'Order not found' 
      });
    }
    
    // Prepare payment data
    const paymentData = {
      key: PAYU_MERCHANT_KEY,
      txnid: orderId,
      amount: amount,
      productinfo: productinfo,
      firstname: firstname,
      email: email,
      phone: phone,
      surl: `${req.headers.origin || 'http://localhost:3000'}/api/payu-v2/success`,
      furl: `${req.headers.origin || 'http://localhost:3000'}/api/payu-v2/failure`,
      hash: '' // Will be generated by PayU
    };
    
    // For PayU v2, we redirect to PayU hosted page
    const payuUrl = `${PAYU_BASE_URL}/_payment`;
    
    res.json({
      success: true,
      payuUrl: payuUrl,
      paymentData: paymentData
    });
  } catch (error) {
    console.error('Error initiating PayU payment:', error);
    res.status(500).json({ 
      success: false, 
      error: 'Failed to initiate PayU payment',
      message: error.message 
    });
  }
});

// PayU v2 success handler
router.post('/success', async (req, res) => {
  try {
    const { txnid, amount, productinfo, firstname, email, hash, status, udf1, udf2, udf3, udf4, udf5 } = req.body;
    
    // Verify the hash to ensure payment authenticity
    const hashString = `${PAYU_MERCHANT_SALT}|${status}|||||||||||${udf5}|${udf4}|${udf3}|${udf2}|${udf1}|${email}|${firstname}|${productinfo}|${amount}|${txnid}|${PAYU_MERCHANT_KEY}`;
    const generatedHash = crypto.createHash('sha512').update(hashString).digest('hex');
    
    if (generatedHash === hash) {
      // Payment verified successfully
      console.log('PayU Payment Successful:', { txnid, amount, productinfo, firstname, email, status });
      
      // Update payment status in database
      await prisma.payments.update({
        where: { orderId: txnid },
        data: { 
          status: 'success',
          payuTxnId: txnid,
          gatewayResponse: JSON.stringify(req.body)
        }
      });
      
      // Update enrollment status if enrollment ID is provided
      if (udf1) {
        try {
          await prisma.aIEnrollments.update({
            where: { id: udf1 },
            data: { 
              isPaid: true,
              transactionId: txnid
            }
          });
          console.log('Enrollment updated successfully:', udf1);
        } catch (dbError) {
          console.error('Error updating enrollment:', dbError);
        }
      }
      
      // Send confirmation email
      // Perform any other post-payment actions
      
      // Redirect to dashboard after successful payment
      res.redirect('/dashboard');
    } else {
      // Hash verification failed
      console.log('PayU Payment Verification Failed:', { txnid, amount, productinfo });
      
      // Update payment status
      await prisma.payments.update({
        where: { orderId: txnid },
        data: { 
          status: 'failed',
          gatewayResponse: JSON.stringify(req.body)
        }
      });
      
      res.sendFile(process.cwd() + '/server/views/payment-failure.html');
    }
  } catch (error) {
    console.error('Error handling PayU success:', error);
    
    // Update payment status
    if (req.body.txnid) {
      await prisma.payments.update({
        where: { orderId: req.body.txnid },
        data: { 
          status: 'error',
          gatewayResponse: JSON.stringify(req.body)
        }
      });
    }
    
    res.status(500).sendFile(process.cwd() + '/server/views/payment-failure.html');
  }
});

// PayU v2 failure handler
router.post('/failure', async (req, res) => {
  try {
    const { txnid, amount, productinfo, firstname, email, status } = req.body;
    
    console.log('PayU Payment Failed:', { txnid, amount, productinfo, firstname, email, status });
    
    // Update payment status in database
    if (txnid) {
      await prisma.payments.update({
        where: { orderId: txnid },
        data: { 
          status: 'failed',
          gatewayResponse: JSON.stringify(req.body)
        }
      });
    }
    
    // Update enrollment status in database
    // Send failure notification
    
    res.sendFile(process.cwd() + '/server/views/payment-failure.html');
  } catch (error) {
    console.error('Error handling PayU failure:', error);
    
    // Update payment status
    if (req.body.txnid) {
      await prisma.payments.update({
        where: { orderId: req.body.txnid },
        data: { 
          status: 'error',
          gatewayResponse: JSON.stringify(req.body)
        }
      });
    }
    
    res.status(500).sendFile(process.cwd() + '/server/views/payment-failure.html');
  }
});

// PayU v2 webhook handler
router.post('/webhook', async (req, res) => {
  try {
    const signature = req.headers['x-payu-signature'];
    const body = req.body;
    
    // Verify webhook signature
    if (!verifyWebhookSignature(body, signature)) {
      console.log('Invalid PayU webhook signature');
      return res.status(400).json({ error: 'Invalid signature' });
    }
    
    // Process webhook event
    const { event, payload } = body;
    
    switch (event) {
      case 'payment.success':
        // Handle successful payment
        await prisma.payments.update({
          where: { orderId: payload.payment.entity.txnid },
          data: { 
            status: 'success',
            payuTxnId: payload.payment.entity.txnid,
            gatewayResponse: JSON.stringify(payload)
          }
        });
        break;
        
      case 'payment.failed':
        // Handle failed payment
        await prisma.payments.update({
          where: { orderId: payload.payment.entity.txnid },
          data: { 
            status: 'failed',
            gatewayResponse: JSON.stringify(payload)
          }
        });
        break;
        
      default:
        console.log('Unhandled PayU webhook event:', event);
    }
    
    res.json({ status: 'ok' });
  } catch (error) {
    console.error('Error processing PayU webhook:', error);
    res.status(500).json({ error: 'Failed to process webhook' });
  }
});

// Health check endpoint
router.get('/health', (req, res) => {
  res.json({ 
    status: 'ok', 
    message: 'PayU v2 integration is running',
    timestamp: new Date().toISOString()
  });
});

export default router;